repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: v1.23.6
    hooks:
      - id: typos
