name: Static analysis and software tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Static analysis and software tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Clippy
        run: rustup component add clippy

      - name: Install Rustfmt
        run: rustup component add rustfmt

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Run Rustfmt
        run: cargo fmt -- --check

      - name: Run tests
        run: cargo test --verbose
